package com.reachmobi.sports.repository.pojo

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class Teams(
    @PrimaryKey(autoGenerate = true)
    val idAPIfootball: String,
    val idLeague: String,
    val idLeague2: Any,
    val idLeague3: Any,
    val idLeague4: Any,
    val idLeague5: Any,
    val idLeague6: Any,
    val idLeague7: Any,
    val idSoccerXML: Any,
    val idTeam: String,
    val intFormedYear: String,
    val intLoved: String,
    val intStadiumCapacity: String,
    val strAlternate: String,
    val strCountry: String,
    val strDescriptionCN: Any,
    val strDescriptionDE: Any,
    val strDescriptionEN: String,
    val strDescriptionES: Any,
    val strDescriptionFR: Any,
    val strDescriptionHU: Any,
    val strDescriptionIL: Any,
    val strDescriptionIT: Any,
    val strDescriptionJP: Any,
    val strDescriptionNL: Any,
    val strDescriptionNO: Any,
    val strDescriptionPL: Any,
    val strDescriptionPT: Any,
    val strDescriptionRU: Any,
    val strDescriptionSE: Any,
    val strDivision: Any,
    val strFacebook: String,
    val strGender: String,
    val strInstagram: String,
    val strKeywords: String,
    val strKitColour1: Any,
    val strKitColour2: Any,
    val strKitColour3: Any,
    val strLeague: String,
    val strLeague2: String,
    val strLeague3: String,
    val strLeague4: String,
    val strLeague5: String,
    val strLeague6: String,
    val strLeague7: String,
    val strLocked: String,
    val strRSS: String,
    val strSport: String,
    val strStadium: String,
    val strStadiumDescription: String,
    val strStadiumLocation: String,
    val strStadiumThumb: String,
    val strTeam: String,
    val strTeamBadge: String,
    val strTeamBanner: String,
    val strTeamFanart1: String,
    val strTeamFanart2: String,
    val strTeamFanart3: String,
    val strTeamFanart4: String,
    val strTeamJersey: String,
    val strTeamLogo: String,
    val strTeamShort: Any,
    val strTwitter: String,
    val strWebsite: String,
    val strYoutube: String
)